#!/bin/bash -e

cd "$(dirname "$0")"

# shellcheck disable=SC1091
. ../push.sh
# shellcheck disable=SC1091
. ../build.env

LOCAL_IMAGE="ubi-nginx:latest"
IMAGE="conjur-nginx"
REDHAT_IMAGE="scan.connect.redhat.com/ospid-9a3dab9b-64c4-4384-882c-80f26ce98607/${IMAGE}"


# Publish git commit and channel tags to the specified registry
TAG="$(git rev-parse --short HEAD | tr -d '\n')"
REGISTRY="$(normalize_repo_name $1)"

tag_and_push_channels "${LOCAL_IMAGE}" "${REGISTRY}${IMAGE}" "${TAG}"

if [[ -n "${TAG_NAME:-}" ]]; then
  # Publish specific tags
  TAG="${TAG_NAME//"v"}"

  tag_and_push "${LOCAL_IMAGE}" "${REGISTRY}${IMAGE}:${NGINX_VERSION}-${TAG}"
  tag_and_push "${LOCAL_IMAGE}" "${REGISTRY}${IMAGE}:${NGINX_VERSION}"

  if summon -f ../secrets.yml bash -c 'docker login scan.connect.redhat.com -u unused -p "${REDHAT_API_KEY}"'; then
    tag_and_push "${LOCAL_IMAGE}" "${REDHAT_IMAGE}:${TAG}"
  else
    echo 'Failed to log in to scan.connect.redhat.com'
    exit 1
  fi
fi  
