#!/bin/bash

set -e

if ! command -v openssl &>/dev/null; then
  echo "openssl could not be found"
  exit 1
fi

OPENSSL_DIR=$(openssl version -d | sed -n 's/.*"\(.*\)"/\1/p')

fips-mode-setup --enable --no-bootcfg

# Prepare additional configuration file for FIPS mode (selectable by OPENSSL_CONF env variable)
OPENSSL_CONF=$(realpath "${OPENSSL_DIR}"/openssl.cnf)
OPENSSL_FIPS_CONF=$(realpath "${OPENSSL_DIR}"/openssl_fips.cnf)
cp "${OPENSSL_CONF}" "${OPENSSL_FIPS_CONF}"

patch --quiet "${OPENSSL_FIPS_CONF}" <<EOF
44a45
> .include /etc/pki/tls/fips_local.cnf
62a64
> default_properties = "fips=yes"
65a68
> fips = fips_sect
EOF

set +e
