#!/bin/bash -e

cd "$(dirname "$0")"

# shellcheck disable=SC1091
. ../push.sh
# shellcheck disable=SC1091
. ../build.env

LOCAL_IMAGE="ubuntu-ruby-fips:latest"
IMAGE="cyberark/ubuntu-ruby-fips"

# Publish git commit and channel tags to the specified registry
TAG="$(git rev-parse --short HEAD | tr -d '\n')"
REGISTRY="$(normalize_repo_name $1)"

tag_and_push_channels "${LOCAL_IMAGE}" "${REGISTRY}${IMAGE}" "${TAG}"

if [[ -n "${TAG_NAME:-}" ]]; then
  # Publish specific tags
  TAG="${TAG_NAME//"v"}"

  tag_and_push "${LOCAL_IMAGE}" "${REGISTRY}${IMAGE}:${UBUNTU_VERSION}-${TAG}"
  tag_and_push "${LOCAL_IMAGE}" "${REGISTRY}${IMAGE}:${UBUNTU_VERSION}"

  main_tag_and_push "${LOCAL_IMAGE}" "${IMAGE}" "${TAG}"
fi
